#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
function main_menu()
{
    while :
    do
echo -ne "\033]0;Information Gathering Tools\007"
resize -s 24 109
clear
echo -e """${red}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${lightcyan}
        =============================================================================
         |                       Information Gathering Tools                        |
         ============================================================================
                                   1.Th3inspector
                                   2.PhoneInfoga
                                   3.InfoG
                                   4.fbi
                                   5.userrecon
                                   m.main menu
        ==============================================================================
"""
read -p "root@Utools:~/WirelessTools " option
case "$option" in
                 4)clear
                 cd fbi
                 chmod +x fbi.py
                 python fbi.py
                 read -p "press any key to return ..."
                 cd ..
                 ;;
                 5)clear
                 cd userrecon
                 chmod +x userrecon.sh
                 ./userrecon.sh
                 read -p "press any key to return ..."
                 cd ..
                 ;;

                 1)clear
                 cd Th3inspector
                 perl Th3inspector.pl
                 read -p "press any key to return ..."
                 cd ..
                 ;;
                 2)clear
                 chmod +x phoneinfoga
                 ./phoneinfoga
                 read -p "press any key to return ..."
                 ;;
                 3)clear
                 cd infog
                 chmod +x infog.sh
                 ./infog.sh
                 read -p "press any key to return ..."
                 cd ..
                 ;;
                 m)clear
                  cd ..
                  ./utools
                ;;

          esac
    done
}
main_menu
