#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
function main_menu()
{
    while :
    do
echo -ne "\033]0;Payload Generator(Utools)\007"
resize -s 24 109
clear
chmod +x *
echo -e """${yellow}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${blue}
            =======================================================================
            |                 Metasploit Payload Generator                        |
            =======================================================================
                          1.Windows(.ExE/.dll)        7.Php(.Php)
                          2.Android(.ApK)             8.Poweshell(.ps1)
                          3.Bash(.sh)                 9.Python(.Py)
                          4.Java(.Jsp)                a.Tomcat(.war)
                          5.OSX (.macho)              b.Asp(.Asp)
                          6.Perl(.pl)                 c.ASPX(.aspx)
                          m.msfconsole                d.Linux(.elf)
                          (00.MAIN MENU)
            ========================================================================
                      EVERY PAYLOAD WILL BE SAVED ON modules FOLDER
            ========================================================================

"""
read -p "root@Utools:~ /PAYLOAD/:" option
case "$option" in
             1)clear
             read -p "Payload Type(exe/dll):" ext
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload $ext $ip $port $type $rev $ps
             ;;
             2)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload APK $ip $port $type $rev $ps
             ;;
             3)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Bash $ip $port $type $rev $ps
             ;;
             4)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Java $ip $port $type $rev $ps
             ;;
             5)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload OSX $ip $port $type $rev $ps
             ;;
             6)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Perl $ip $port $type $rev $ps
             ;;
             7)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload PHP $ip $port $type $rev $ps
             ;;
             8)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Powershell $ip $port $type $rev $ps
             ;;
             9)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Python $ip $port $type $rev $ps
             ;;
             a)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Tomcat $ip $port $type $rev $ps
             ;;
             b)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload ASP $ip $port $type $rev $ps
             ;;
             c)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload ASPX $ip $port $type $rev $ps
             ;;
             d)clear
             read -p "Enter Your Ip(Public/Private):" ip
             read -p "Enter Any Port You Like(4444):" port
             read -p "Enter Type(CMD/MSF)If You Dont Know Skip:" type
             read -p "Enter Type of Payload(BIND/REVERSE):" rev
             read -p "Enter Port Type(TCP/HTTP/HTTPS/FIND_PORT)" ps
             ./payload Linux $ip $port $type $rev $ps
             ;;
             m)msfconsole
             ;;
             00)clear
             cd ..
             ./utools
             ;;
          esac
    done
}
main_menu
