#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
function main_menu()
{
    while :
    do
echo -ne "\033]0;Webapp Pentest(Utools)\007"
resize -s 24 109
clear
echo -e """${yellow}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${blue}
            =======================================================================
            |                        Webapp Pentest Tools                         |
            =======================================================================
                              1.Rapid Scan         5.SiteBroker
                              2.WPExploit          6.RED_HAWK
                              3.XSStrike
                              4.XAttacker
                              m.main Menu
            ========================================================================
"""
read -p "root@Utools:~" option
case "$option" in
               1)clear
                cd rapidscan
                read -p "Enter Targeted Website Name::" url
                python rapidscan.py $url
                read -p "press any key to return ..."
                cd ..
                ;;
                2)clear
                cd WPExploit
                read -p "Enter Targeted Website Name::" url2
                chmod +x wpexploit.sh
                ./wpexploit.sh $url2
                read -p "press any key to return ..."
                ;;
                3)clear
                cd XSStrike
                read -p "Enter Targeted Website Name::" url3
                python xsstrike.py -u $url3
                cd ..
                read -p "press any key to return ..."
                ;;
                4)clear
                cd XAttacker
                perl XAttacker.pl
                cd ..
                read -p "press any key to return ..."
                ;;
                5)clear
                cd SiteBroker
                python SiteBroker.py
                cd ..
                read -p "press any key to return ..."
                ;;
                6)clear
                cd RED_HAWK
                php rhawk.php
                cd ..
                read -p "press any key to return ..."
                ;;
                m)clear
                cd ..
                ./utools
                ;;
          esac
    done
}
main_menu
