#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
function main_menu()
{
    while :
    do
echo -ne "\033]0;WEBSHELL DOWNLOADER(Utools)\007"
resize -s 24 109
clear
echo -e """${yellow}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${blue}
            =======================================================================
            |                        WEBSHELL DOWNLOADER                        |
            =======================================================================
                AVILABLE SHELL(SINGLE DOWNLOAD OPTION IS NOT AVILABLE ('-'))
            +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
                          |R57(PHP)                   |B37(PHP)
                          |WSO(PHP)                   |ANI Shell(PHP)
                          |C99(PHP)                   |CMD(PHP)
                          |Dhanusk(PHP)               |Pro.php
                          |.Devlopers Backdoor(php)   |LinuNix(PHP)
                          |IndoXploit v3 Web Shell    |404.php
                          |SYSMLIK 403
                          |CPanel Cracker(PHP)
                          m.Main Menu
            xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

            ||||||||||||||||||||||||||ENTER A To DOWNLOAD ALL ||||||||||||||||||||
            ------------------------------zip-------------------------------------
            ======================================================================
                                    m.main menu
           ========================================================================
"""
read -p "root@Utools:~ /Webshell" option
case "$option" in
                A)clear
                git clone https://github.com/JoyGhoshs/Webshell
                echo '+++++++++++++++++++++++++++'
                echo 'Saved In modules/Webshell'
                echo '++++++++++++++++++++++++++'
                read -p "press any key to return ..."
                cd ..
                ;;
                m)clear
                cd ..
                ./utools
                ;;
          esac
    done
}
main_menu
