#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
echo -ne "\033]0;Wordlist Genarator(Easy Cli)(Utools)\007"
resize -s 24 109
clear
echo -e """${yellow}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${blue}
            =======================================================================
            |                     Wgen(wordlist Generator)                        |
            =======================================================================
"""
read -p "Enter Minimum Length Of Password::" Min
read -p "Enter Maximum Lenth Of Password::" Max
read -p "Enter characters/Numbers For Wordlist::" charc
cd python-wordlist-generator
python wgen.py -chr $charc -min $Min -max $Max
echo """     =======================================================================
             Output Has been Saved On python-wordlist-generator/output/wordlist.txt
      """
read -p "press any key to return ..."
cd ..
