#!/bin/bash
#Project Utools2
#Project From Joy JoyGhosh
#Joychondroghosh@gmail.com
cyan='\e[0;36m'
lightcyan='\e[96m'
green='\e[0;32m'
lightgreen='\e[1;32m'
white='\e[1;37m'
red='\e[1;31m'
yellow='\e[1;33m'
blue='\e[1;34m'
function main_menu()
{
    while :
    do
echo -ne "\033]0;Wireless Attack Tool(Utools)\007"
resize -s 24 109
clear
echo -e """${red}
           _________________________________________________________________________
            ██╗   ██╗████████╗ ██████╗  ██████╗ ██╗     ███████╗██████╗     ██████╗
            ██║   ██║╚══██╔══╝██╔═══██╗██╔═══██╗██║     ██╔════╝╚════██╗   ██╔═████╗
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ███████╗ █████╔╝   ██║██╔██║
            ██║   ██║   ██║   ██║   ██║██║   ██║██║     ╚════██║██╔═══╝    ████╔╝██║
            ╚██████╔╝   ██║   ╚██████╔╝╚██████╔╝███████╗███████║███████╗██╗╚██████╔╝
             ╚═════╝    ╚═╝    ╚═════╝  ╚═════╝ ╚══════╝╚══════╝╚══════╝╚═╝ ╚═════╝
             ______________________________________________________________________
                                        BY JOY GHOSH
             ----------------------------------------------------------------------
"""
echo -e """${lightcyan}
        =============================================================================
         |                             WirelessAttack Tools                        |
         ============================================================================
                                        1.Airattackit
                                        2.Airgeddon
                                        3.Wifite
                                        b.Back To Main Menu
        ==============================================================================
"""
read -p "root@Utools:~/WirelessTools " option
case "$option" in
               1)clear
                cd Airattackit
                chmod +x *
                ./airattack
                 read -p "press any key to return ..."
                 cd ..
                 ;;
               2)clear
                cd airgeddon
                chmod +x *
                ./airgeddon.sh
                read -p "press any key to return ..."
                cd ..
                ;;
                3)clear
                 wifite
                 ;;
                b)clear
                cd ..
                ./utools
                ;;






          esac
    done
}
main_menu
